server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: keynote-service
          uri: lb://KEYNOTE-SERVICE
          predicates:
            - Path=/api/keynotes/**
          filters:
            - CircuitBreaker=keynoteCircuitBreaker

        - id: conference-service
          uri: lb://CONFERENCE-SERVICE
          predicates:
            - Path=/api/conferences/**
          filters:
            - CircuitBreaker=conferenceCircuitBreaker

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/conference-realm
          jwk-set-uri: http://keycloak:8080/realms/conference-realm/protocol/openid-connect/certs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  circuitbreaker:
    instances:
      keynoteCircuitBreaker:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000
        permitted-number-of-calls-in-half-open-state: 3
      conferenceCircuitBreaker:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000
